import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, LineChart, Line, AreaChart, Area, ScatterChart, Scatter, ZAxis, ReferenceLine, ComposedChart } from 'recharts'
import { competitorScores, financeTrend, riskMap, waterfall } from '../data/dashboardData'

const tooltipStyle={background:'#11141b',border:'1px solid rgba(255,255,255,.08)',borderRadius:12,fontSize:11,color:'#fff'}

export function CompetitorChart(){return <ResponsiveContainer width="100%" height={260}><BarChart data={competitorScores} layout="vertical" margin={{left:12,right:18}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" domain={[0,100]}/><YAxis dataKey="name" type="category" width={72}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="qualification" stackId="a" fill="#6d5dfc" radius={[5,0,0,5]}/><Bar dataKey="price" stackId="a" fill="#65a7ff" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer>}

export function WinProfitChart(){return <ResponsiveContainer width="100%" height={270}><ComposedChart data={financeTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="discount"/><YAxis yAxisId="left"/><YAxis yAxisId="right" orientation="right"/><Tooltip contentStyle={tooltipStyle}/><ReferenceLine yAxisId="right" y={0} stroke="#f87171" strokeDasharray="4 4"/><Line yAxisId="left" type="monotone" dataKey="win" stroke="#7c6cff" strokeWidth={2.5} dot={{r:3}}/><Area yAxisId="right" type="monotone" dataKey="profit" fill="#38bdf822" stroke="#38bdf8" strokeWidth={2}/></ComposedChart></ResponsiveContainer>}

export function WaterfallChart(){return <ResponsiveContainer width="100%" height={260}><BarChart data={waterfall}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip contentStyle={tooltipStyle}/><ReferenceLine y={0} stroke="#6b7280"/><Bar dataKey="value" fill="#7768ff" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer>}

export function RiskScatter(){return <ResponsiveContainer width="100%" height={285}><ScatterChart margin={{top:15,right:20,bottom:10,left:0}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="impact" name="Влияние" domain={[0,105]}/><YAxis type="number" dataKey="likelihood" name="Вероятность" domain={[0,105]}/><ZAxis type="number" dataKey="exposure" range={[80,500]}/><Tooltip cursor={{strokeDasharray:'3 3'}} contentStyle={tooltipStyle}/><ReferenceLine x={70} stroke="#f59e0b55"/><ReferenceLine y={70} stroke="#f59e0b55"/><Scatter data={riskMap} fill="#fb7185"/></ScatterChart></ResponsiveContainer>}

export function ReadinessArea({data}){return <ResponsiveContainer width="100%" height={220}><AreaChart data={data}><defs><linearGradient id="grad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#7c6cff" stopOpacity={.35}/><stop offset="95%" stopColor="#7c6cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="value" stroke="#7c6cff" fill="url(#grad)" strokeWidth={2}/></AreaChart></ResponsiveContainer>}
