import { AlertOctagon, BadgeDollarSign, TimerReset, UserX, Siren, Activity } from 'lucide-react'
import { Card, CardHeader, KPI, DataTable, Badge, DecisionBar } from '../components/ui'
import { RiskScatter } from '../charts/charts'
import { riskMap } from '../data/dashboardData'
import { Page } from './Overview'

export default function Risks(){const rows=riskMap.map((r,i)=>({...r,owner:['Лена','Сергей','Ольга','Юрист','Финансы'][i],status:['Открыт','Просрочен','В работе','Не начат','Наблюдение'][i]}));return <Page title="Риски" subtitle="Реестр, экспозиция и план реагирования">
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><KPI label="Критические" value="4" sub="2 требуют решения сегодня" tone="red" icon={<AlertOctagon size={16}/>}/><KPI label="Экспозиция" value="6,4 млн ₽" sub="До мер — 9,8 млн ₽" tone="red" icon={<BadgeDollarSign size={16}/>}/><KPI label="Просрочено" value="5" sub="3 на критическом пути" tone="red" icon={<TimerReset size={16}/>}/><KPI label="Без владельца" value="3" sub="1 критический риск" tone="red" icon={<UserX size={16}/>}/><KPI label="Реализовано" value="1" sub="Рост стоимости ИБ" tone="amber" icon={<Siren size={16}/>}/><KPI label="Тренд" value="↑ 12%" sub="Экспозиция ухудшается" tone="red" icon={<Activity size={16}/>}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.05fr_.95fr]"><Card><CardHeader eyebrow="Матрица" title="Вероятность × влияние" description="Размер точки — финансовая экспозиция"/><div className="p-3"><RiskScatter/></div></Card><Card><CardHeader eyebrow="Приоритет" title="Критические риски"/><div className="space-y-3 p-5">{[['ИБ и лицензии','Допуск и до −3,2 млн ₽','Сергей · просрочено'],['Генподрядчик','Блокирует договорную схему','Ольга · 25 июля'],['Демпинг выше предела','Риск убыточной победы','Лена · до торгов'],['Опыт не подтвержден','Потеря до 10 баллов','Юрист · 28 июля']].map(x=><div key={x[0]} className="rounded-xl border border-rose-400/10 bg-rose-400/[.035] p-3"><div className="flex justify-between gap-3"><p className="text-xs font-medium">{x[0]}</p><Badge tone="red">Критично</Badge></div><p className="mt-2 text-[11px] text-zinc-500">{x[1]}</p><p className="mt-2 text-[10px] text-zinc-600">{x[2]}</p></div>)}</div></Card></div>
<Card className="mt-4"><CardHeader eyebrow="Реестр" title="Активные риски"/><DataTable columns={[{key:'id',label:'ID'},{key:'name',label:'Риск'},{key:'likelihood',label:'Вероятность',render:v=>`${v}%`},{key:'impact',label:'Влияние',render:v=>`${v}%`},{key:'exposure',label:'Экспозиция',render:v=>`${v} млн ₽`},{key:'owner',label:'Владелец'},{key:'status',label:'Статус',render:v=><Badge tone={v==='Просрочен'||v==='Не начат'?'red':v==='Открыт'?'amber':'blue'}>{v}</Badge>}]} rows={rows}/></Card>
<Card className="mt-4"><CardHeader eyebrow="Зависимости" title="Критическая цепочка"/><div className="grid gap-2 p-5 md:grid-cols-6">{['ИБ','Генподряд','Договорная схема','Экономика','Предел демпинга','Go / No Go'].map((x,i)=><div key={x} className="relative rounded-xl border border-white/[.06] bg-white/[.025] p-3 text-center text-xs text-zinc-300">{x}{i<5&&<span className="absolute -right-2 top-1/2 hidden -translate-y-1/2 text-zinc-700 md:block">→</span>}</div>)}</div></Card>
<div className="mt-4"><DecisionBar title="Выбрать стратегию реагирования по ИБ" text="Риск влияет одновременно на допуск, выбор генподрядчика, стоимость контракта и финальную экономику." actions={['Передать риск','Снизить риск','Принять решение']}/></div>
</Page>}
