import { Award, ShieldCheck, Trophy, Crosshair, Banknote, Target } from 'lucide-react'
import { Card, CardHeader, KPI, DataTable, Badge, DecisionBar, ProgressRow } from '../components/ui'
import { CompetitorChart, WinProfitChart } from '../charts/charts'
import { competitorScores } from '../data/dashboardData'
import { Page } from './Overview'

export default function Win(){const rows=competitorScores.map((x,i)=>({...x,place:i+1,prob:[80,100,75,35][i]}));return <Page title="Вероятность победы" subtitle="Сценарная модель конкурсного результата">
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><KPI label="Победа" value="62%" sub="Диапазон 45–72%" trend="−4 п.п." tone="amber" icon={<Target size={16}/>}/><KPI label="Наш балл" value="86,4" sub="Из 100 возможных" trend="+4,2 доступно" tone="green" icon={<Award size={16}/>}/><KPI label="Место" value="2 из 4" sub="Позиция неустойчива" tone="amber" icon={<Trophy size={16}/>}/><KPI label="Допуск" value="88%" sub="2 незакрытых условия" tone="amber" icon={<ShieldCheck size={16}/>}/><KPI label="Разрыв" value="−2,7" sub="До лидера" tone="red" icon={<Crosshair size={16}/>}/><KPI label="Цена победы" value="28,4 млн ₽" sub="Экономически убыточна" tone="red" icon={<Banknote size={16}/>}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader eyebrow="Рейтинг" title="Прогнозный балл участников" description="Цена + квалификация"/><div className="p-4"><CompetitorChart/></div></Card><Card><CardHeader eyebrow="Наш балл" title="Где теряем баллы"/><div className="space-y-5 p-5"><ProgressRow label="Цена" value={86} meta="25,8 / 30"/><ProgressRow label="Количество договоров" value={76} meta="21 / 24,5"/><ProgressRow label="Стоимость договоров" value={96} meta="23,6 / 24,5"/><ProgressRow label="Специалисты" value={76} meta="16 / 21"/><div className="rounded-xl border border-violet-400/15 bg-violet-400/[.05] p-3 text-xs text-zinc-400">Потенциал без дополнительного демпинга: <b className="text-white">+5–8 баллов</b>.</div></div></Card></div>
<Card className="mt-4"><CardHeader eyebrow="Конкуренты" title="Сценарий участия"/><DataTable columns={[{key:'name',label:'Участник'},{key:'prob',label:'Вероятность участия',render:v=>`${v}%`},{key:'price',label:'Цена',render:v=>`${v.toFixed(1)} балла`},{key:'qualification',label:'Квалификация'},{key:'total',label:'Итого'},{key:'place',label:'Место',render:v=><Badge tone={v===1?'green':v===2?'amber':'neutral'}>{v}</Badge>}]} rows={rows}/></Card>
<Card className="mt-4"><CardHeader eyebrow="Чувствительность" title="Вероятность победы против прибыли" description="Демпинг повышает шанс, но разрушает экономику"/><div className="p-4"><WinProfitChart/></div></Card>
<div className="mt-4"><DecisionBar title="Сначала добрать квалификационные баллы" text="Подтверждение договоров и специалистов дает больший эффект, чем дополнительное снижение цены, и не ухудшает маржу." actions={['Сценарий с тестовым','Утвердить стратегию']}/></div>
</Page>}
