import { Users, Handshake, ShieldCheck, UserMinus, Gauge, Link2 } from 'lucide-react'
import { Card, CardHeader, KPI, DataTable, Badge, DecisionBar, ProgressRow, StatusIcon } from '../components/ui'
import { team, partners, licenses } from '../data/dashboardData'
import { Page } from './Overview'

export default function Delivery(){return <Page title="Исполнение" subtitle="Команда, подрядчики, лицензии и мобилизация">
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><KPI label="Команда" value="82%" sub="15 из 18 ролей закрыты" tone="amber" icon={<Users size={16}/>}/><KPI label="Подрядчики" value="4 из 5" sub="Нет резервного ИБ-партнера" tone="amber" icon={<Handshake size={16}/>}/><KPI label="Лицензии" value="87%" sub="2 позиции на проверке" tone="amber" icon={<ShieldCheck size={16}/>}/><KPI label="Дефицит" value="3 роли" sub="Backend, DevOps, контент" tone="red" icon={<UserMinus size={16}/>}/><KPI label="Готовность" value="74%" sub="Исполнительный контур" tone="amber" icon={<Gauge size={16}/>}/><KPI label="Зависимости" value="2" sub="Критические" tone="red" icon={<Link2 size={16}/>}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><Card><CardHeader eyebrow="Команда" title="Роли и загрузка"/><DataTable columns={[{key:'role',label:'Роль'},{key:'required',label:'Нужно'},{key:'assigned',label:'Назначено'},{key:'load',label:'Загрузка',render:v=><div className="w-28"><ProgressRow label="" value={v} meta={`${v}%`}/></div>},{key:'status',label:'Статус',render:v=><span className="flex items-center gap-2"><StatusIcon status={v}/>{v}</span>}]} rows={team}/></Card><Card><CardHeader eyebrow="Партнерский контур" title="Подрядчики"/><div className="space-y-3 p-5">{partners.map(p=><div key={p.name} className="surface-soft rounded-xl p-3"><div className="flex items-start justify-between"><div><p className="text-xs font-medium">{p.name}</p><p className="mt-1 text-[11px] text-zinc-500">{p.work}</p></div><Badge tone={p.risk==='Высокий'?'red':p.risk==='Средний'?'amber':'green'}>{p.risk}</Badge></div><div className="mt-3"><ProgressRow label={p.contract} value={p.readiness}/></div></div>)}</div></Card></div>
<div className="mt-4 grid gap-4 xl:grid-cols-2"><Card><CardHeader eyebrow="Допуски" title="Лицензии и принадлежность"/><DataTable columns={[{key:'name',label:'Лицензия'},{key:'owner',label:'У кого'},{key:'status',label:'Статус',render:v=><span className="flex items-center gap-2"><StatusIcon status={v}/>{v}</span>}]} rows={licenses}/></Card><Card><CardHeader eyebrow="Мобилизация" title="Календарь готовности"/><div className="space-y-5 p-5">{[{name:'Договоры с партнерами',value:72,meta:'до 30 июля'},{name:'Закрытие дефицита команды',value:48,meta:'до 15 августа'},{name:'Подтверждение лицензий',value:67,meta:'до 5 августа'},{name:'Готовность к старту',value:35,meta:'сентябрь'}].map(x=><ProgressRow key={x.name} label={x.name} value={x.value} meta={x.meta}/>)}</div></Card></div>
<Card className="mt-4"><CardHeader eyebrow="Консорциум" title="Карта ответственности"/><DataTable columns={[{key:'work',label:'Работы'},{key:'exec',label:'Исполнитель'},{key:'legal',label:'Ответственность перед заказчиком'},{key:'money',label:'Получатель денег'}]} rows={[{work:'Техническое сопровождение',exec:'Реактив',legal:'Генподрядчик',money:'Реактив'},{work:'Информационное сопровождение',exec:'BLACK',legal:'Генподрядчик',money:'BLACK'},{work:'Информационная безопасность',exec:'ИБ-партнер',legal:'Генподрядчик',money:'ИБ-партнер'},{work:'Лицензионное соответствие',exec:'Генподрядчик',legal:'Генподрядчик',money:'—'}]}/></Card>
<div className="mt-4"><DecisionBar title="Закрыть подрядчика по ИБ и три дефицитные роли" text="Без этих ресурсов исполнительная готовность остается ниже порога начала контракта, а нагрузка на текущую команду превышает безопасный уровень." actions={['Утвердить команду','Подписать подрядчика']}/></div>
</Page>}
