import { Receipt, Wallet, Coins, CircleDollarSign, Percent, TrendingDown } from 'lucide-react'
import { Card, CardHeader, KPI, DataTable, Badge, DecisionBar } from '../components/ui'
import { WaterfallChart, WinProfitChart } from '../charts/charts'
import { Page } from './Overview'

const scenarios=[{s:'Оптимистичный',d:'18%',gp:'Айти Ресурс',p:'+1,6 млн',m:'10,5%',r:'Условно'},{s:'Базовый',d:'23%',gp:'Айти Ресурс',p:'−0,5 млн',m:'−3,8%',r:'Пересчитать'},{s:'Легион',d:'23%',gp:'Легион',p:'−1,7 млн',m:'−14,3%',r:'Стоп'},{s:'Стрессовый',d:'30%',gp:'Айти Ресурс',p:'−3,4 млн',m:'−33,3%',r:'Стоп'}]
export default function Finance(){return <Page title="Финансовая модель" subtitle="От бюджета заказчика до проектной прибыли Реактива">
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><KPI label="Цена ГК" value="29,95 млн ₽" sub="Демпинг 23%" icon={<Receipt size={16}/>}/><KPI label="Доход Реактива" value="13,1 млн ₽" sub="Включая агентское" icon={<Wallet size={16}/>}/><KPI label="Себестоимость" value="13,6 млн ₽" sub="64% данных подтверждено" tone="amber" icon={<Coins size={16}/>}/><KPI label="Прибыль" value="−0,5 млн ₽" sub="До дополнительного резерва" tone="red" icon={<CircleDollarSign size={16}/>}/><KPI label="Маржа" value="−3,8%" sub="Цель — не ниже 12%" tone="red" icon={<Percent size={16}/>}/><KPI label="Предел демпинга" value="21,7%" sub="Текущий — 23%" tone="red" icon={<TrendingDown size={16}/>}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.05fr_.95fr]"><Card><CardHeader eyebrow="Денежный поток" title="Водопад экономики"/><div className="p-4"><WaterfallChart/></div></Card><Card><CardHeader eyebrow="Качество модели" title="Структура затрат и достоверность"/><div className="space-y-3 p-5">{[['ФОТ','3,88 млн ₽','Подтверждено','green'],['Накладные','3,71 млн ₽','Методика','blue'],['ИБ','0,8–4,0 млн ₽','Не подтверждено','red'],['БГ и кредит','0,85 млн ₽','Не проверено','amber'],['Резерв риска','0 ₽','Не заложен','red']].map(x=><div className="surface-soft flex items-center justify-between rounded-xl p-3" key={x[0]}><div><p className="text-xs">{x[0]}</p><p className="mt-1 text-[11px] text-zinc-500">{x[1]}</p></div><Badge tone={x[3]}>{x[2]}</Badge></div>)}<div className="pt-2"><div className="flex justify-between text-xs"><span>Достоверность модели</span><b>64%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/[.05]"><div className="h-full w-[64%] rounded-full bg-violet-500"/></div></div></div></Card></div>
<Card className="mt-4"><CardHeader eyebrow="Сценарии" title="Сравнение вариантов экономики"/><DataTable columns={[{key:'s',label:'Сценарий'},{key:'d',label:'Демпинг'},{key:'gp',label:'Генподряд'},{key:'p',label:'Прибыль'},{key:'m',label:'Маржа'},{key:'r',label:'Решение',render:v=><Badge tone={v==='Стоп'?'red':v==='Пересчитать'?'amber':'green'}>{v}</Badge>}]} rows={scenarios}/></Card>
<Card className="mt-4"><CardHeader eyebrow="Чувствительность" title="Прибыль и вероятность при изменении демпинга"/><div className="p-4"><WinProfitChart/></div></Card>
<div className="mt-4"><DecisionBar title="Утвердить минимальную доходность и ценовой предел" text="Без фиксированной нормы прибыли команда не сможет определить, где заканчивается допустимая конкурентная цена и начинается убыточная победа." actions={['Пересчитать себестоимость','Утвердить предел']}/></div>
</Page>}
